<?php 
	return [
		'MARQUES PREMIUM' => [
			1 => 'Bridgestone',
			2 => 'Continental',
			3 => 'Dunlop',
			4 => 'Goodyear',
			5 => 'Hankook',
			6 => 'Michelin',
			7 => 'Pirelli',
			7 => 'Pirelli',
		],
		'MARQUES QUALITY' => [
			8 => 'Bf Goodrich',
			9 => 'Black Star',
			10 => 'Cooper',
			11 => 'Falken',
			12 => 'Federal',
			13 => 'Firestone',
			14 => 'Fulda',
			15 => 'General Tire',
			16 => 'Kleber',
			17 => 'Kumho',
			18 => 'Laufenn',
			19 => 'Marshal',
			20 => 'Maxxis',
			21 => 'Nankang',
			22 => 'Nexen',
			23 => 'Nokian',
			24 => 'Toyo',
			25 => 'Uniroyal',
			26 => 'Vredestein',
			27 => 'Yokohama',
		],
		'MARQUES ECO BUDGET' => [
			'28' => 'Atturo',
			'29' => 'Autogreen',
			'30' => 'Firemax',
			'31' => 'Habilead',
			'32' => 'Haida',
			'33' => 'Imperial',
			'34' => 'Keter',
			'35' => 'Kinforest',
			'36' => 'Mazzini',
			'37' => 'Nordexx',
			'38' => 'Powertrac',
			'39' => 'Riken Europe',
			'40' => 'Sunny',
			'40' => 'Sunwide',
		],
		'MARQUES RECHAPES' => [
			'41' => 'Nortenha'
		],
	];